name: LeafLow自动签到

on:
  schedule:
    - cron: '30 0 * * *'  # 每天 8:30 UTC+8
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        working-directory: leaflow-checkin
        run: |
          pip install requests
          
      - name: Prepare config
        working-directory: leaflow-checkin
        run: python3 get_tokens_helper.py
        env:
          LEAFLOW_COOKIES: ${{ secrets.LEAFLOW_COOKIES }}
          
      - name: Run checkin
        working-directory: leaflow-checkin
        run: python3 checkin_token.py --notify
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
